title: 승환's 블로그
description: blog of seunghwanho made from github&0pe

url: http://developstudio.0pe.kr/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: hoseunghwan
   twitter: brianmaierjr
   facebook: brianmaierjr
   email: andyho0124@gmail.com

google_analytics: "UA-58263416-1"
